name: Setup
description: "Setup project"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure node
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build app
      run: npm run build
      shell: bash
