name: Quote
description: "Create Quote"
runs:
  using: "composite"
  steps:
    - name: Fetch quote
      run: echo "QUOTE_RESPONSE=$(curl -s https://zenquotes.io/api/today)" >> $GITHUB_ENV
      shell: bash

    - name: Comment with quote
      uses: actions/github-script@v7
      with:
        script: |
          const { QUOTE_RESPONSE } = process.env;
          const response = JSON.parse(QUOTE_RESPONSE);
	        const quote = response[0].q;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Today's quote is: ${quote}`
          });
